#!name=Youtube Ad Full v3
#!desc=Youtube Ad Full v3
# IOS > 15
# 删除 瀑布流、视频、搜索中出现的广告和Shorts，
# 删除 Shorts 内的视频广告
# 广告信息可能有遗漏，可能偶现广告
# inspired by @Choler & @DivineEngine & @app2smile

[Url Rewrite]
^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads - reject-200
^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking) - reject-200
^https?:\/\/s\.youtube\.com\/api\/stats\/qoe\?adcontext - reject-200

(^https?:\/\/[\w-]+\.googlevideo\.com\/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+) $1$2$3 302
^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?)).+&oad - reject-200

[Script]
# 该模块已足够全面，无需其他规则混用，防止重写规则被破坏。
youtube1 = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|reel\/reel_watch_sequence)\?,requires-body=1,binary-body-mode=1,max-size=3145728,script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/dist/youtube.request.beta.js
youtube2 = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting)\?,requires-body=1,binary-body-mode=1,max-size=3145728,script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/dist/youtube.request.beta.js

[MITM]
hostname = %APPEND% -redirector*.googlevideo.com,*.googlevideo.com,www.youtube.com,s.youtube.com,youtubei.googleapis.com
