# reference: https://github.com/deezertidal/shadowrocket-rules/blob/main/modules/HistoryPrice.sgmodule
#!name=JD_Price_History
#!desc=Show price history on JD item panel
#!system=ios


[Script]
JD_Price = type=http-response,requires-body=1,pattern=^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=(wareBusiness|serverConfig|basicConfig),script-path=https://raw.githubusercontent.com/deezertidal/private/main/jdprice.js


[MITM]
hostname = %APPEND% api.m.jd.com
