#!name=Reddit Adblocker
#!desc=Reddit Adblocker
#!author=ddgksf2013 (Qx/Surge)
#!notes=origin script url: https://raw.githubusercontent.com/ddgksf2013/Rewrite/refs/heads/master/AdBlock/RedditAds.conf

[MITM]
hostname = %APPEND% gql-fed.reddit.com

[Script]
reddit=type=http-response,pattern=^https?:\/\/gql-fed\.reddit\.com\/$,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/refs/heads/master/reddit.js