#!name=Weibo V2
#!desc=Weibo app removes ad V2.
#!source @bai1zi
#!system=ios

[Script]
# 首页 签到,发布按钮,侧边栏,右上角红包,侧边栏提醒,超话tab悬浮,顶部直播
weibo = type=http-response,pattern=^https:\/\/api\.weibo\.cn\/2\/checkin\/show\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/weibo.js
weibo = type=http-response,pattern=^https:\/\/api\.weibo\.cn\/2\/client\/publisher_list\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/weibo.js
weibo = type=http-response,pattern=^https:\/\/api\.weibo\.cn\/2\/push\/active\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/weibo.js
# 详情页 超话,评论区,个人主页,我的页面,信息流,视频流,视频号,话题卡片
weibo = type=http-response,pattern=^https:\/\/api\.weibo\.cn\/2\/cardlist\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/weibo.js
weibo = type=http-response,pattern=^https:\/\/api\.weibo\.cn\/2\/comments\/build_comments\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/weibo.js
weibo = type=http-response,pattern=^https:\/\/api\.weibo\.cn\/2\/profile\/container_timeline\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/weibo.js
weibo = type=http-response,pattern=^https:\/\/api\.weibo\.cn\/2\/profile\/me\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/weibo.js
weibo = type=http-response,pattern=^https:\/\/api\.weibo\.cn\/2\/statuses\/container_timeline(_topic|_unread)?\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/weibo.js
weibo = type=http-response,pattern=^https:\/\/api\.weibo\.cn\/2\/statuses\/unread_hot_timeline\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/weibo.js
weibo = type=http-response,pattern=^https:\/\/api\.weibo\.cn\/2\/statuses\/extend\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/weibo.js
weibo = type=http-response,pattern=^https:\/\/api\.weibo\.cn\/2\/video\/tiny_stream_video_list\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/weibo.js
weibo = type=http-response,pattern=^https:\/\/api\.weibo\.cn\/2\/!\/huati\/discovery_home_bottom_channels\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/weibo.js
# 消息页
weibo = type=http-response,pattern=^https:\/\/api\.weibo\.cn\/2\/messageflow\/notice\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/weibo.js
# 发现页 热门微博信息流,搜索列表,热搜提醒,猜你想搜
weibo = type=http-response,pattern=^https:\/\/api\.weibo\.cn\/2\/page\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/weibo.js
weibo = type=http-response,pattern=^https:\/\/api\.weibo\.cn\/2\/search\/container_timeline\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/weibo.js
weibo = type=http-response,pattern=^https:\/\/api\.weibo\.cn\/2\/search\/finder\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/weibo.js
weibo = type=http-response,pattern=^https:\/\/api\.weibo\.cn\/2\/searchall\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/weibo.js
# 开屏广告
weibo = type=http-response,pattern=^https:\/\/adstrategy\.biz\.weibo\.com\/v2\/strategy\/ad\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/weibo.js
weibo = type=http-response,pattern=^https:\/\/sdkapp\.uve\.weibo\.com\/interface\/sdk\/sdkad\.php$,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/weibo.js
weibo = type=http-response,pattern=^https:\/\/wbapp\.uve\.weibo\.com\/wbapplua\/wbpullad\.lua\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/weibo.js
noRedirect = type=http-response,pattern=^https:\/\/(sinaurl|t)\.cn\/,requires-body=0,max-size=0,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/noRedirect.js
# > 微博自定义tab皮肤
weibo_main = type=http-response,pattern=^https://api.weibo.cn/2/!/client/light_skin,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/zmqcherish/proxy-script/main/weibo_main.js
# > 微博非会员设置tab皮肤
weibo_main = type=http-response,pattern=^https://new.vip.weibo.cn/littleskin/preview,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/zmqcherish/proxy-script/main/weibo_main.js


[MITM]
hostname = %APPEND% api.weibo.cn, mapi.weibo.com, sdkapp.uve.weibo.com, card.weibo.com, weibo.com, weibo.cn, shop.sc.weibo.com, new.vip.weibo.cn