#!name=Weibo Ad Blocker
#!desc=Weibo app removes ads
#!source=@ddgksf2013
#!originURL=https://github.com/ddgksf2013/Rewrite/raw/master/AdBlock/Weibo.conf
#!system=ios

[Url Rewrite]
# 微博_每日一次的开屏广告请求
^https?:\/\/boot.*weibo\.com\/v\d\/ad\/realtime - reject-200
# 微博_去除底部超话栏表层浮icon及tips
^https?:\/\/api\.weibo\.cn\/\d\/!\/huati\/discovery_home_bottom_getdotinfo - reject-dict
# 微博_屏蔽首页左上角每日的弹窗tips
^https?:\/\/m?api\.weibo\.c(n|om)\/\d/push/daily - reject-dict
# 微博_应用内弹窗广告
^https?:\/\/(preload-click|preload-impression)\.uve\.weibo\.com\/(interface\/wbpullad\/wbpullad_click\.php|wbapplua\/get_wbpullad_log\.lua) - reject
# 微博_屏蔽sdkconfig请求
^https?:\/\/sdkapp\.uve\.weibo\.com\/interface\/sdk\/sdkconfig\.php - reject
# 微博_Spotlight
^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/hot\/hours_spotlight - reject-dict

[Script]
# 微博_开屏广告预加载处理
weiboad=type=http-response,pattern=^https?:\/\/boot.*weibo\.com\/v\d\/ad\/preload,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
# 微博_未登陆状态下首页信息流处理
weiboad=type=http-response,pattern=^https?:\/\/api\.weibo\.cn\/\d\/\w{5}\/(statuses_unread_hot_timeline|timeline),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
# 微博_视频信息处理
weiboad=type=http-response,pattern=^https?:\/\/api\.weibo\.cn\/\d\/video\/tiny_stream_mid_detail,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
# 微博_屏蔽发现页面搜索框热词
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/\w{5}\/cardlist,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
# 微博_自定义tab皮肤
weiboad=type=http-response,pattern=^https://api.weibo.cn/2/!/client/light_skin,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
# 微博_非会员设置tab皮肤
weiboad=type=http-response,pattern=^https://new.vip.weibo.cn/littleskin/preview,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
# 微博_去广告以及去除各部分推广模块
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/(searchall|page\?|messageflow),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/statuses/(unread_)?friends(/|_)timeline,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/groups/timeline,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/statuses/(container_timeline|unread_hot_timeline|extend|video_mixtimeline|unread_topic_timeline),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/profile/(me|container_timeline),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/video/(community_tab|remind_info|tiny_stream_video_list),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/search/(finder|container_timeline|container_discover),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/(checkin/show|\!/live/media_homelist|comments/build_comments|container/get_item),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/cardlist,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js

[MITM]
hostname = %APPEND% api.weibo.cn, api.weibo.com, *.api.weibo.cn, *.api.weibo.com, mapi.weibo.com, mapi.weibo.cn, *.uve.weibo.com, new.vip.weibo.cn, boot.biz.weibo.com