#!name=YouTube Premium Experimental
#!desc=Youtube Ad Full blocker with PIP player (Experimental)
#!arguments=requestService:https://stream.maasea.workers.dev,blockUpload:true,blockImmersive:true,blockShorts:false,captionLang:off,lyricLang:off
# Origin Author: @Maasea
# Translated and refined for shadowrocket

[Url Rewrite]
^https:\/\/youtubei\.googleapis\.com\/(youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch|log_event))(\?(.*))?$ {{{requestService}}}/$1?blockUpload={{{blockUpload}}}&blockImmersive={{{blockImmersive}}}&blockShorts={{{blockShorts}}}&captionLang={{{captionLang}}}&lyricLang={{{lyricLang}}}&$4 _ 307
(^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&ack.*) "https://init-stream.maasea.workers.dev/?url=$1" header

[MITM]
hostname = %APPEND% *.googlevideo.com, youtubei.googleapis.com