#!name=YouTube premium
#!desc=Youtube Ad Full blocker with PIP player
# Origin Author: @DivineEngine, @app2smile, @Maasea, @VirgilClyne
# Merged and released by @ddgksf2013 in form of qx
# Translated by @bai1zi in form of ShadowRocket

[Url Rewrite]
^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?)).+&oad - reject-200
# ======= Universal Ad Request ======= #
^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads - reject-200 
^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking) - reject-200
^https?:\/\/s\.youtube\.com\/api\/stats\/qoe\?adcontext - reject-200
# ======= General Video Ad request ======= #
(^https?:\/\/[\w-]+\.googlevideo\.com\/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+) $1$2$3 302

[Script]
# ======= Search|Play Page|Short Video ||| PiP|Background Play ======= #
youtube = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting),requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/dist/youtube.response.beta.js

[MITM]
hostname = %APPEND% -redirector*.googlevideo.com,*.googlevideo.com,www.youtube.com,s.youtube.com,youtubei.googleapis.com